name: Continuous integration

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

env:
  NODE_VERSION: "16.x"

jobs:
  quality:
    name: Check the quality of the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
